services:
  vcc-vdv457-export:
    entrypoint: >
      sh -c "
        pip install debugpy && PYTHONPATH=src python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m vccvdv457export main
      "
    ports:
      - "5678:5678"
  vcc-api:
    entrypoint: >
      sh -c "
        pip install debugpy && PYTHONPATH=src python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn src.vccapi.api:app --port 8080 --host 0.0.0.0
      "
    ports:
      - "${VCC_API_PORT}:8080"
      - "5678:5678"

networks:
  vcc: