services:
  vcc-database:
    image: mysql:latest
    container_name: vcc-database
    restart: unless-stopped
    networks:
      - vcc
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: vccdb
      MYSQL_USER: vccuser
      MYSQL_PASSWORD: vccpasswd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
  vcc-proxy:
    image: httpd:2.4
    container_name: vcc-proxy
    restart: unless-stopped
    networks:
      - vcc
    ports:
      - "${VCC_API_PORT}:443"
    entrypoint: ["/bin/sh", "-c", "
      htpasswd -bc /usr/local/apache2/conf/.htpasswd ${VCC_USERNAME} ${VCC_PASSWORD} &&
      echo 'Include /usr/local/apache2/conf/extra/httpd-vcc-proxy.conf' >> /usr/local/apache2/conf/httpd.conf && 
      httpd-foreground"]
    environment:
      - VCC_USERNAME
      - VCC_PASSWORD
    volumes:
      - ./src/vccproxy/httpd-vcc-proxy.conf:/usr/local/apache2/conf/extra/httpd-vcc-proxy.conf:ro
      - ${VCC_PROXY_SSL_CERT_FILENAME}:/etc/ssl/certs/cert.crt
      - ${VCC_PROXY_SSL_CHAIN_FILEMAME}:/etc/ssl/certs/chain.crt
      - ${VCC_PROXY_SSL_KEY_FILENAME}:/etc/ssl/private/key.key
    depends_on:
      - vcc-api
  vcc-vdv452-import:
    build:
      context: .
      dockerfile: ./src/vccvdv452import/Dockerfile
    container_name: vcc-vdv452-import
    restart: unless-stopped
    networks:
      - vcc
    environment:
      - VCC_DEBUG
      - VCC_VDV452_IMPORT_INTERVAL
      - VCC_VDV452_ADAPTER_TYPE
    volumes:
      - ${VCC_VDV452_IMPORT_DIRECTORY}:/data
    depends_on:
      "vcc-database":
        condition: service_healthy
  vcc-md-import:
    build:
      context: .
      dockerfile: ./src/vccmdimport/Dockerfile
    container_name: vcc-md-import
    restart: unless-stopped
    networks:
      - vcc
    environment:
      - VCC_DEBUG
      - VCC_MD_IMPORT_INTERVAL
      - VCC_MD_IMPORT_ADAPTER_TYPE
    volumes:
      - ${VCC_MD_IMPORT_DIRECTORY}:/data
    depends_on:
      "vcc-database":
        condition: service_healthy
  vcc-api:
    build:
      context: .
      dockerfile: ./src/vccapi/Dockerfile
    container_name: vcc-api
    restart: unless-stopped
    networks:
      - vcc
    expose:
      - "8080"
    environment:
      - VCC_DEBUG
      - VCC_USERNAME
      - VCC_PASSWORD
      - VCC_API_SCHEME
      - VCC_API_HOSTNAME
      - VCC_API_PORT
    volumes:
      - ${VCC_API_DATA_DIRECTORY}:/data
      - ${VCC_API_LOG_DIRECTORY}:/logs
    depends_on:
      "vcc-database":
        condition: service_healthy
  vcc-vdv457-export:
    build:
      context: .
      dockerfile: ./src/vccvdv457export/Dockerfile
    container_name: vcc-vdv457-export
    restart: unless-stopped
    networks:
      - vcc
    environment:
      - VCC_DEBUG
      - VCC_VDV457_EXPORT_INTERVAL
      - VCC_VDV457_EXPORT_CONVERT_2
      - VCC_VDV457_EXPORT_ADAPTER_TYPE_2
      - VCC_VDV457_EXPORT_CONVERT_3
      - VCC_VDV457_EXPORT_ADAPTER_TYPE_3
    volumes:
      - ${VCC_VDV457_EXPORT_DATA_DIRECORY}:/data/input
      - ${VCC_VDV457_EXPORT_OUTPUT_DIRECTORY_2}:/data/vdv4572
      - ${VCC_VDV457_EXPORT_OUTPUT_DIRECTORY_3}:/data/vdv4573
    depends_on:
      "vcc-database":
        condition: service_healthy

networks:
  vcc: